### ISSUE TITLE
Intro video 용량 압축 및 수정

### ISSUE THREAD

**Issue by andysooho** [seungy0/crush_client#19]
인트로 영상 압축해서 용량 줄이기
fit을 cover로 바꿔서 비율 이상하게 보이지 않게 하기
영샹 약간 흐리게 수정

**Comment by seungy0** [comment]
@andysooho 이슈 단위로 PR 바람

**Comment by andysooho** [comment]
현재는 임시 인트로 영상임. 추후 정식 인트로 영상으로 교체 예정.
