### ISSUE TITLE
앱 재실행시 유저정보 초기화

### ISSUE THREAD

**Issue by andysooho** [seungy0/crush_client#46]
앱 재실행 혹은 로그아웃 시 유저정보가 초기화됨

**Comment by seungy0** [comment]
@andysooho 그럼 로그아웃 했다가 다시 들어가면 uid 가 변해??

**Comment by andysooho** [comment]
@seungy0 ㄴㄴ uid는 그대로고 필드값이 기본값으로 초기화 되는거?
name 처리가 빡쎘는데 해결햇슈
